server:
  port: 8989
  servlet:
    context-path: /cmfl
    jsp:
      init-parameters:
        development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cmfl
    username: root
    password: 123456
  mvc:
    view:
      prefix: /
      suffix: .jsp
  aop:
    proxy-target-class: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  redis:
    host: 192.168.245.14
    port: 8001
mybatis:
  type-aliases-package: com.baizhi.bts.entity
  mapper-locations: classpath:com/baizhi/bts/mapper/*.xml
logging:
  level:
    root: info
    com.baizhi.bts.dao: debug
